### ISSUE TITLE
Possible missing eslint rules compared to m-c

### ISSUE THREAD

**Issue by jobisoft** [thunderbird/webext-experiments#36]
@kewisch : This is not a request to add these rules, but just a capture of the current situation. I run ../mach eslint on the two API folders and got these errors:

- [example, lots of similar errors] : 'window' is never reassigned. Use 'const' instead. --- prefer-const (eslint)
- [calendar/parent/ext-calendarItemAction.js:130:11] : error  'global' is not defined. --- no-undef (eslint)
- [calendar/parent/ext-calendarItemDetails.js:101:10] : error  'context' is defined but never used. Allowed unused args must match /^_/u. --- no-unused-vars (eslint)

**Comment by kewisch** [comment]
Interesting. The no-unused-vars errors I resolved using some more specific rules in the overrides. We could add `_` to context, or actually remove it from the parameter list instead of using a specific rule.

For no-undef, `global` is used in some ext- code, and is an allowed global here:
https://searchfox.org/comm-central/source/mail/components/extensions/parent/.eslintrc.js#12

The prefer-const one comes from here, we should probably add all these rules:
https://searchfox.org/comm-central/source/.eslintrc.js#70
